`define SYSTEM_CONTROL                       8'h00
`define DISPLAY_CONTROL                      8'h01
`define MEMORY_CONTROL                       8'h02
`define LED_CONTROL                          8'h03
`define CAMERA_CONTROL                       8'h04
`define SYSTEM_STATUS                        8'h05
`define WR_BURST_SIZE_LOW                    8'h06
`define WR_BURST_SIZE_HIGH                   8'h07
`define BURST_WR_DATA                        8'h08
`define RD_BURST_SIZE_LOW                    8'h09
`define RD_BURST_SIZE_HIGH                   8'h0A
`define BURST_RD_DATA                        8'h0B
`define CAPTURE_CONTROL                      8'h0C
`define CAPTURE_STATUS                       8'h0D
`define CAPTURE_SIZE_0                       8'h0E
`define CAPTURE_SIZE_1                       8'h0F
`define CAPTURE_SIZE_2                       8'h10
`define CAPTURE_SIZE_3                       8'h11
`define CAPT_FRM_CHECKSUM_0                  8'h12
`define CAPT_FRM_CHECKSUM_1                  8'h13
`define REPLAY_RATE_CONTROL                  8'h14
`define MIC_CONTROL                          8'h15
`define CAPT_BYTE_COUNT_0                    8'h16
`define CAPT_BYTE_COUNT_1                    8'h17
`define CAPT_BYTE_COUNT_2                    8'h18
`define CAPT_BYTE_COUNT_3                    8'h19
`define CAPTURE_FRM_LEN_BYTE0                8'h1A
`define CAPTURE_FRM_LEN_BYTE1                8'h1B
`define CAPTURE_FRM_LEN_BYTE2                8'h1C
`define CAPTURE_FRM_SIDEBAND                 8'h1D
`define FPGA_VERSION_MINOR                   8'h1E
`define FPGA_VERSION_MAJOR                   8'h1F

`define READ_ON                              8'h80
`define RD_ADDR                              8'h81

`define DEBUG_CONTROL                        8'hE7
`define DBG_FRM_PER_SEC                      8'hE8
`define DBG_TOTAL_FRM0                       8'hE9
`define DBG_TOTAL_FRM1                       8'hEA
`define DBG_TOTAL_FRM2                       8'hEB
`define DBG_TOTAL_FRM3                       8'hEC
`define DBG_TOTAL_FRM4                       8'hED
`define DBG_TOTAL_FRM5                       8'hEE
`define DBG_TOTAL_FRM6                       8'hEF
`define DBG_TOTAL_FRM7                       8'hF0
`define DBG_TOTAL_BYTE0                      8'hF1
`define DBG_TOTAL_BYTE1                      8'hF2
`define DBG_TOTAL_BYTE2                      8'hF3
`define DBG_TOTAL_BYTE3                      8'hF4
`define DBG_TOTAL_BYTE4                      8'hF5
`define DBG_TOTAL_BYTE5                      8'hF6
`define DBG_TOTAL_BYTE6                      8'hF7
`define DBG_TOTAL_BYTE7                      8'hF8
`define DBG_LINE_PER_FRM0                    8'hF9
`define DBG_LINE_PER_FRM1                    8'hFA
`define DBG_BYTE_PER_LINE0                   8'hFB
`define DBG_BYTE_PER_LINE1                   8'hFC
`define DBG_BYTE_PER_FRM0                    8'hFD
`define DBG_BYTE_PER_FRM1                    8'hFE
`define DBG_BYTE_PER_FRM2                    8'hFF

